version: '3.8'

services:
  nexusbank:
    build: .
    ports:
      - "8080:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
    volumes:
      - ./bankdata.json:/app/bankdata.json
    restart: unless-stopped 